spring:
  application:
    name: libraryapi

  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: yasuke
    password: pedrotomaz09172314
    driver-class-name: org.postgresql.Driver